/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.view;

import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.controller.TypeDAO;
import org.model.Type;

/**
 *
 * @author Amil
 */
public class AddTypes extends javax.swing.JInternalFrame {
   DefaultTableModel model;
    /**
     * Creates new form AddTypes
     */
    public AddTypes() {
        
        initComponents();
        jTextField1_Id.setVisible(false);
        jLabel5.setVisible(false);
         model =new DefaultTableModel(null,new String[]{"typesID","name",});
        jTable1.setModel(model);
        
    }
    
    public void loadData(){
    clearModel();
    TypeDAO tDAO =new TypeDAO();
   ArrayList<Type> cList=tDAO.fetchData();
   for(int i=0;i<cList.size();i++){
       
  
   model.addRow(new Object[] {cList.get(i).getTypeID(),cList.get(i).getName()});
            }
           }
public void clearModel(){
    int count =model.getRowCount();
    for(int i=0;i<count;i++){
        model.removeRow(0);
    }
}
public void clearText(){
    jTextField1_Id.setText("");
    jTextField2_Name.setText("");
   
}
public void clearLabel(){
     jLabel1_validationName.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1_Save = new javax.swing.JButton();
        jButton1_Update = new javax.swing.JButton();
        jButton2_Delete = new javax.swing.JButton();
        jButton1_Show = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2_Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_Id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1_Clear = new javax.swing.JButton();
        jLabel1_validationName = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1_Save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_Save.setText("Save");
        jButton1_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_SaveActionPerformed(evt);
            }
        });

        jButton1_Update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_Update.setText("Update");
        jButton1_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_UpdateActionPerformed(evt);
            }
        });

        jButton2_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2_Delete.setText("Delete");
        jButton2_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_DeleteActionPerformed(evt);
            }
        });

        jButton1_Show.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_Show.setText("Show");
        jButton1_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_ShowActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTextField2_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2_NameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2_NameKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name");

        jTextField1_Id.setEditable(false);
        jTextField1_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_IdActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Id");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Type Information");

        jButton1_Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_Clear.setText("Clear");
        jButton1_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1_Clear)
                                .addGap(40, 40, 40)
                                .addComponent(jButton1_Show)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2_Delete)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1_Update)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1_Save))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField1_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1_validationName)
                            .addComponent(jTextField2_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1_validationName)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1_Show)
                        .addComponent(jButton1_Clear))
                    .addComponent(jButton2_Delete)
                    .addComponent(jButton1_Update)
                    .addComponent(jButton1_Save))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_SaveActionPerformed
boolean error = false;
        if(jTextField1_Id.getText().equals("")==false){
      JOptionPane.showMessageDialog(null,"Please Clear All Fields First");
      return;
 }
 if(jTextField2_Name.getText().trim().isEmpty()){
   jLabel1_validationName.setText("Name can not be empty");
   error = true;
 }
 if(error ==false){
        String name =jTextField2_Name.getText();
        if(new TypeDAO().checkTypes(jTextField2_Name.getText())){
            JOptionPane.showMessageDialog(rootPane,"Dupicate Type Name");
        }
        else{
 Type ob=new Type();
 ob.setName(name);
   TypeDAO tDAO=new TypeDAO();
        int result =tDAO.saveData(ob) ;     
        if(result==1){
            JOptionPane.showMessageDialog(rootPane,"Recorde Save");
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Recorde not Save");
        }
        }
loadData();
clearLabel();
clearText();

 }
    }//GEN-LAST:event_jButton1_SaveActionPerformed
 
    private void jButton1_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_UpdateActionPerformed
     boolean error  =  false;
        if(jTextField2_Name.getText().trim().isEmpty()){
   jLabel1_validationName.setText("Name can not be empty");
   error = true;
 }
        if(error == false){
        int id=Integer.parseInt(jTextField1_Id.getText());
        String name =jTextField2_Name.getText();
        if(new TypeDAO().checkTypes(jTextField2_Name.getText())){
            JOptionPane.showMessageDialog(rootPane,"Dupicate Type Name");
        }
        else{
        Type ob=new Type();
        ob.setTypeID(id);
        ob.setName(name);
         TypeDAO tDAO=new TypeDAO();
       int result =tDAO.updateRecord(ob);
       if(result==1){
            JOptionPane.showMessageDialog(rootPane,"Recorde Update");
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Recorde not Update");
        }
        }
         loadData();
        clearLabel();
        clearText();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_UpdateActionPerformed

    private void jButton2_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_DeleteActionPerformed
        if (!jTextField1_Id.getText().trim().isEmpty()) {
            int answer = JOptionPane.showConfirmDialog(rootPane, "Are you Sure???", "Conformation", JOptionPane.YES_NO_OPTION);
            if (answer == 0) {
                int id = Integer.parseInt(jTextField1_Id.getText());

                Type ob = new Type();
                ob.setTypeID(id);
                TypeDAO tDAO = new TypeDAO();
                int result = tDAO.deleteRecord(ob);
                if (result == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Medicine Type delete");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Cannot delete a parent row: a foreign key constraint fails");
                }
                loadData();
            }
            else {
            }
        } 
        else{
     JOptionPane.showMessageDialog(rootPane, "Please select medicine First");
    }
    }//GEN-LAST:event_jButton2_DeleteActionPerformed

    private void jButton1_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_ShowActionPerformed
loadData();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_ShowActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
jTextField1_Id.setVisible(true);
        jLabel5.setVisible(true);
        int row =jTable1.getSelectedRow();
        jTextField1_Id.setText(jTable1.getValueAt(row,0).toString());
        jTextField2_Name.setText(jTable1.getValueAt(row,1).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_IdActionPerformed

    private void jButton1_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_ClearActionPerformed
      // TODO add your handling code here:
      jTextField1_Id.setVisible(false);
        jLabel5.setVisible(false);
      clearLabel();
      clearText();
    }//GEN-LAST:event_jButton1_ClearActionPerformed

    private void jTextField2_NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2_NameKeyTyped
        char c=evt.getKeyChar();

    if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACKSPACE)||  c==KeyEvent.VK_DELETE ))
        evt.consume();  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_NameKeyTyped

    private void jTextField2_NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2_NameKeyReleased
      jLabel1_validationName.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_NameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTypes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Clear;
    private javax.swing.JButton jButton1_Save;
    private javax.swing.JButton jButton1_Show;
    private javax.swing.JButton jButton1_Update;
    private javax.swing.JButton jButton2_Delete;
    private javax.swing.JLabel jLabel1_validationName;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_Id;
    private javax.swing.JTextField jTextField2_Name;
    // End of variables declaration//GEN-END:variables
}
