/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.view;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import static org.util.Util.*;

public class Frame extends javax.swing.JFrame {
    public Frame() {
        initComponents();
        System.out.println(isAdmin);
    }
 public void close(){
 
 WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
 Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1_desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1_AddMedicine = new javax.swing.JMenuItem();
        jMenuItem2_AddSuppliers = new javax.swing.JMenuItem();
        jMenuItem3_AddTypes = new javax.swing.JMenuItem();
        jMenuItem4_AddUser = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1_Sales = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        SalesDetail = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1_desktopLayout = new javax.swing.GroupLayout(jDesktopPane1_desktop);
        jDesktopPane1_desktop.setLayout(jDesktopPane1_desktopLayout);
        jDesktopPane1_desktopLayout.setHorizontalGroup(
            jDesktopPane1_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1503, Short.MAX_VALUE)
        );
        jDesktopPane1_desktopLayout.setVerticalGroup(
            jDesktopPane1_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1_AddMedicine.setText("Add Medicine");
        jMenuItem1_AddMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_AddMedicineActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1_AddMedicine);

        jMenuItem2_AddSuppliers.setText("AddSuppliers");
        jMenuItem2_AddSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2_AddSuppliersActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2_AddSuppliers);

        jMenuItem3_AddTypes.setText("AddTypes");
        jMenuItem3_AddTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_AddTypesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3_AddTypes);

        jMenuItem4_AddUser.setText("Add User");
        jMenuItem4_AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4_AddUserActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4_AddUser);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu3);

        jMenu2.setText("Transaction");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1_Sales.setText("Sales");
        jMenuItem1_Sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_SalesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1_Sales);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Report");

        SalesDetail.setText("SalesDetail");
        SalesDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesDetailActionPerformed(evt);
            }
        });
        jMenu4.add(SalesDetail);

        jMenuItem1.setText("SalesReport");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("SalesItemReport");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("ExpiryMedicine");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Exit");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1_desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1_desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2_AddSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2_AddSuppliersActionPerformed

//jInternalFrame1.dispose();

AddSuppliers ob=new AddSuppliers();
jDesktopPane1_desktop.add(ob);
ob.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2_AddSuppliersActionPerformed

    private void jMenuItem3_AddTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_AddTypesActionPerformed

//jInternalFrame1.dispose();

AddTypes ob=  new AddTypes();
jDesktopPane1_desktop.add(ob);
ob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3_AddTypesActionPerformed

    private void jMenuItem4_AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4_AddUserActionPerformed
if(isAdmin ==true){
 AddUser ob=  new AddUser();
jDesktopPane1_desktop.add(ob);
ob.setVisible(true);
}
else{
    UserInfo ob=new UserInfo();
    jDesktopPane1_desktop.add(ob);
ob.setVisible(true);
    
}
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4_AddUserActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1_AddMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_AddMedicineActionPerformed

AddMedicine ob = new AddMedicine();
jDesktopPane1_desktop.add(ob);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1_AddMedicineActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1_SalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_SalesActionPerformed

Transaction  ob=new Transaction();
jDesktopPane1_desktop.add(ob);
ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1_SalesActionPerformed

    private void SalesDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesDetailActionPerformed
     SalesDetail ob =new SalesDetail();
     jDesktopPane1_desktop.add(ob);
ob.setVisible(true);
    }//GEN-LAST:event_SalesDetailActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     SalesReport ob = new SalesReport();
     jDesktopPane1_desktop.add(ob);
     ob.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        SalesItemReport ob =  new SalesItemReport();
        jDesktopPane1_desktop.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ExpiryMedicine ob =  new ExpiryMedicine();
        jDesktopPane1_desktop.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.setProperty("sun.java2d.uiScale","2");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SalesDetail;
    private javax.swing.JDesktopPane jDesktopPane1_desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem1_AddMedicine;
    private javax.swing.JMenuItem jMenuItem1_Sales;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem2_AddSuppliers;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem3_AddTypes;
    private javax.swing.JMenuItem jMenuItem4_AddUser;
    // End of variables declaration//GEN-END:variables
}
